version: '3.8'

services:
  api:
    #build: ./services/web
    build: .
    container_name: flask_api
    command: python main.py
    # command: python main.py run -h 0.0.0.0
    # command: gunicorn -w 2 -t 3600 -b :5000 api:api --reload
    # stdin_open: true
    # tty: true
    environment:
      STAGE: test
      #SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:postgres@db:15432/tarefa_api
      DATABASE_URL: postgresql://postgres:postgres@localhost:15432/tarefa_api
    volumes:
      #- ./services/web/:/usr/src/app/
      - .:/reports
      # - ./app:/usr/src/app/app
    ports:
      - 5000:5000
    #env_file:
    #  - ./.env.dev


   
  #db-postgres-compose:
  #  image: postgres
  #  environment:
  #    POSTGRES_PASSWORD: "postgres"
  #  ports:
  #    - "15432:5432" 
  #  volumes:
      #- c:/docker/data/postgres:/var/lib/postgresql/data
      # - c:\docker\data\postgres:/var/lib/postgresql/data 
      # - /home/axel/Dev/Docker/postgres/data:/var/lib/postgresql/data
      #- /home/renatogroffe/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
  #  networks:
  #    - postgres-compose-network
      
  #db-pgadmin-compose:
  #  image: dpage/pgadmin4
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL    : "axelpatton@gmail.com"
  #    PGADMIN_DEFAULT_PASSWORD : "demo123"
  #  ports:
  #    - "16543:80"
  #  depends_on:
  #    - db-postgres-compose
  #  networks:
  #    - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge